openapi: 3.0.0
info:
  version: '1.0'
  title: inditex-test
  description: API made for the Inditex technical test.
  termsOfService: ''
  contact:
    name: Axel Negro Perez
    url: https://www.linkedin.com/in/axel-negro-perez
    email: negroperezaxel@gmail.com
servers:
  - url: 'http://localhost:8080'
    description: Localhost
paths:
  '/brands/{brand_id}/products/{product_id}/prices':
    get:
      tags:
        - Prices
      summary: Get product price of the brand by date
      description: Endpoint in charge of getting the product price of the brand by date.
      operationId: get-brands-brand_id-products-product_id-prices
      parameters:
        - name: application_date
          in: query
          description: Date of application to get the price of the product for that date.
          required: true
          schema:
            type: string
            format: date-time
            pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}T([0-9]{2}:){2}[0-9]{2}'
        - name: brand_id
          in: path
          description: Id of the brand.
          required: true
          schema:
            type: number
        - name: product_id
          in: path
          description: Id of the product.
          required: true
          schema:
            type: number
      responses:
        '200':
          $ref: '#/components/responses/GetPrices200Response'
        '400':
          $ref: '#/components/responses/GetPrices400Response'
        '500':
          $ref: '#/components/responses/GetPrices500Response'
      servers:
        - url: 'http://localhost:8080'
          description: Localhost
tags:
  - name: Prices
    description: Tag used for the prices-related endpoints.
components:
  responses:
    GetPrices200Response:
      description: 'Price for the GET - /brands/{brand_id}/products/{product_id}/prices endpoint.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Price'
    GetPrices500Response:
      description: 'Response used for the 500 responses in GET - /brands/{brand_id}/products/{product_id}/prices endpoint.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Message'
          examples:
            Example:
              value:
                code: INDITEX-ERROR-00500
                message: Something has gone wrong.
    GetPrices400Response:
      description: 'Response used for the 400 responses in GET - /brands/{brand_id}/products/{product_id}/prices endpoint.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Message'
          examples:
            Example 1:
              value:
                code: INDITEX-ERROR-00400
                message: Bad request.
  schemas:
    Price:
      type: object
      title: Price
      description: Model for the price
      properties:
        id:
          type: integer
          description: Id of the price.
          format: int64
        product_id:
          type: integer
          description: Id of the product.
          format: int64
        brand_id:
          type: integer
          description: Id of the brand.
          format: int64
        start_date:
          type: string
          description: Starting date of the price application.
          format: date-time
          pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}T([0-9]{2}:){2}[0-9]{2}'
        end_date:
          type: string
          description: End date of the price application.
          format: date-time
          pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}T([0-9]{2}:){2}[0-9]{2}'
        price:
          type: number
          description: Price of the product to apply
          format: double
    Message:
      type: object
      title: Message
      description: Model for the message
      properties:
        code:
          type: string
        message:
          type: string
